apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    control-plane: controller-manager
  name: mystatefulset-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - mystatefulset-webhook-service.mystatefulset-system.svc
    - mystatefulset-webhook-service.mystatefulset-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: mystatefulset-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    control-plane: controller-manager
  name: mystatefulset-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
