# permissions for end users to edit mystatefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mystatefulset-editor-role
rules:
- apiGroups:
  - apps.mystatefulset.com
  resources:
  - mystatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mystatefulset.com
  resources:
  - mystatefulsets/status
  verbs:
  - get
