# Default values for mystatefulset
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: bryantrh/mystatefulset-controller
  tag: 0.0.2-209d505
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Webhook configurations
webhook:
  enabled: true
  certManager:
    enabled: true
    
# Controller configurations
controller:
  manager:
    args:
      - --leader-elect
      - --health-probe-bind-address=:8081
      - --metrics-bind-address=127.0.0.1:8080
    env:
      - name: ENABLE_WEBHOOKS
        value: "true"
